import { PrinterIcon } from "@heroicons/react/24/outline";
import { Button, Modal } from "@heroui/react";
import { formatMoney } from "@/lib/admin-format";
import { paymentMethodLabels, type CheckoutInvoice } from "./data";
import type { PaymentTotals } from "./payment-state";

export function InvoicePreviewModal({ invoice, totals, onClose }: Readonly<{ invoice: CheckoutInvoice; totals: PaymentTotals; onClose: () => void }>) {
  return <Modal isOpen onOpenChange={(open) => { if (!open) onClose(); }}><Modal.Backdrop><Modal.Container size="md" placement="center" scroll="inside"><Modal.Dialog className="rounded-xl border border-admin-border bg-admin-surface"><Modal.CloseTrigger className="rounded-lg print:hidden" /><Modal.Header className="border-b border-admin-border px-6 py-5"><div><p className="text-xs font-bold tracking-[0.18em] text-admin-accent">YABAI NAIL SALON</p><Modal.Heading className="mt-1 text-xl font-bold text-admin-ink">Hóa đơn thanh toán</Modal.Heading><p className="mt-1 text-xs text-admin-muted">{invoice.customer.name} · {invoice.appointment.date} lúc {invoice.appointment.time}</p></div></Modal.Header><Modal.Body className="space-y-5 px-6 py-5"><section><h3 className="text-sm font-bold text-admin-ink">Khách hàng</h3><p className="mt-2 text-sm">{invoice.customer.name} · {invoice.customer.phone}</p><p className="text-xs text-admin-muted">{invoice.appointment.date} lúc {invoice.appointment.time}</p></section><section><h3 className="text-sm font-bold text-admin-ink">Dịch vụ</h3><ul className="mt-2 divide-y divide-admin-border text-sm"><InvoiceRow name={invoice.currentService.name} amount={invoice.currentService.price} />{invoice.additionalItems.map((item) => <InvoiceRow key={item.id} name={item.name} amount={item.price} />)}</ul></section><dl className="space-y-2 border-y border-admin-border py-4 text-sm"><SummaryRow label="Tạm tính" value={formatMoney(totals.subtotal)} /><SummaryRow label="Giảm giá" value={`-${formatMoney(totals.discount)}`} /><SummaryRow label="Tổng thanh toán" value={formatMoney(totals.grandTotal)} strong /></dl><p className="text-sm text-admin-muted">Phương thức: <strong className="text-admin-ink">{invoice.paymentMethod ? paymentMethodLabels[invoice.paymentMethod] : "Chưa chọn"}</strong></p>{invoice.orderNote ? <p className="whitespace-pre-wrap rounded-lg bg-admin-soft p-3 text-xs text-admin-muted">{invoice.orderNote}</p> : null}</Modal.Body><Modal.Footer className="border-t border-admin-border px-6 py-4 print:hidden"><Button variant="outline" className="rounded-lg border-admin-border" onPress={onClose}>Đóng</Button><Button variant="primary" className="rounded-lg" onPress={() => window.print()}><PrinterIcon className="size-4" />In hóa đơn</Button></Modal.Footer></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>;
}

function InvoiceRow({ name, amount }: Readonly<{ name: string; amount: number }>) { return <li className="flex justify-between gap-4 py-2"><span>{name}</span><strong>{formatMoney(amount)}</strong></li>; }
function SummaryRow({ label, value, strong = false }: Readonly<{ label: string; value: string; strong?: boolean }>) { return <div className="flex justify-between gap-4"><dt className={strong ? "font-bold text-admin-ink" : "text-admin-muted"}>{label}</dt><dd className={strong ? "font-bold text-admin-accent" : "font-semibold text-admin-ink"}>{value}</dd></div>; }

